-- =====================================================================
-- Beer & Beverages  —  PostgreSQL 16 schema
-- Project: "Довідка пабів м. Львів" (mobile rebuild)
-- Stack:   React Native + Expo  /  FastAPI  /  PostgreSQL + PostGIS
--
-- Conventions
--   * BIGINT identity PKs (matches old Hibernate generation)
--   * snake_case table & column names
--   * TIMESTAMPTZ everywhere — server is UTC, clients convert
--   * citext for case-insensitive email / username uniqueness
--   * Soft delete via deleted_at on user-facing entities
--   * GEOGRAPHY(POINT, 4326) for "real-world" lat/lon (PostGIS)
--   * JSONB for OCR payloads, push data, achievement requirements
--   * Junction tables use composite PKs
-- =====================================================================

-- ---------- Extensions ----------
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ---------- Enums ----------
CREATE TYPE user_role               AS ENUM ('user', 'admin', 'moderator');
CREATE TYPE price_category          AS ENUM ('budget', 'mid', 'premium', 'luxury');
CREATE TYPE friendship_status       AS ENUM ('pending', 'accepted', 'blocked');
CREATE TYPE friend_request_status   AS ENUM ('pending', 'accepted', 'declined', 'cancelled');
CREATE TYPE friend_group_role       AS ENUM ('member', 'admin');
CREATE TYPE raid_status             AS ENUM ('planned', 'ongoing', 'completed', 'cancelled');
CREATE TYPE raid_rsvp_status        AS ENUM ('going', 'maybe', 'declined');
CREATE TYPE check_payment_method    AS ENUM ('d20_dice', 'voluntary', 'agreement', 'split');
CREATE TYPE check_participant_status AS ENUM ('invited', 'joined', 'ready', 'left');
CREATE TYPE dice_proposal_status    AS ENUM ('pending', 'accepted', 'declined', 'completed', 'cancelled');
CREATE TYPE dice_vote               AS ENUM ('pending', 'accept', 'decline');
-- ----- Tavern Tales (AI Dungeon Master) -----
CREATE TYPE dnd_mode                AS ENUM ('munchkin', 'normal', 'dungeon_master_pro');
CREATE TYPE dnd_class               AS ENUM (
    'barbarian','bard','cleric','druid','fighter','monk',
    'paladin','ranger','rogue','sorcerer','warlock','wizard'
);
CREATE TYPE dnd_alignment           AS ENUM (
    'lawful_good',    'neutral_good',    'chaotic_good',
    'lawful_neutral', 'true_neutral',    'chaotic_neutral',
    'lawful_evil',    'neutral_evil',    'chaotic_evil'
);
CREATE TYPE dnd_session_status      AS ENUM ('active', 'paused', 'completed', 'abandoned');
CREATE TYPE dnd_message_role        AS ENUM ('user', 'assistant', 'system', 'dice_roll', 'narration');
CREATE TYPE achievement_category    AS ENUM ('social', 'exploration', 'spending', 'quiz', 'kind_soul', 'misc');
CREATE TYPE notification_type       AS ENUM (
    'friend_request',
    'friend_accepted',
    'raid_invite',
    'raid_reminder',
    'achievement_unlocked',
    'check_shared',
    'check_invite',
    'check_split_completed',
    'dice_proposal_created',
    'dice_proposal_resolved',
    'kind_soul_awarded',
    'dnd_session_reminder',
    'system'
);
CREATE TYPE push_platform           AS ENUM ('ios', 'android', 'web');
CREATE TYPE drink_type              AS ENUM ('beer', 'cocktail', 'wine', 'spirit', 'non_alcoholic', 'other');
CREATE TYPE conversation_type       AS ENUM ('direct', 'group');
CREATE TYPE conversation_role       AS ENUM ('member', 'admin');
CREATE TYPE presence_status         AS ENUM ('online', 'away', 'offline');

-- =====================================================================
-- 1. Geography & reference data
-- =====================================================================

CREATE TABLE cities (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            TEXT        NOT NULL UNIQUE,
    name            TEXT        NOT NULL,
    country_code    CHAR(2)     NOT NULL DEFAULT 'UA',
    timezone        TEXT        NOT NULL DEFAULT 'Europe/Kyiv',
    location        GEOGRAPHY(POINT, 4326),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_cities_location ON cities USING GIST (location);

-- Atmospheres ("vibes") — used by bars and races
CREATE TABLE vibes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            TEXT        NOT NULL UNIQUE,
    name            TEXT        NOT NULL,
    description     TEXT,
    icon_url        TEXT
);

-- Drinks catalog — referenced by races and (later) menu features
CREATE TABLE drinks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            TEXT        NOT NULL UNIQUE,
    name            TEXT        NOT NULL,
    type            drink_type  NOT NULL DEFAULT 'other',
    description     TEXT,
    image_url       TEXT
);

-- Fantasy races assigned via quiz
CREATE TABLE races (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            TEXT        NOT NULL UNIQUE,
    name            TEXT        NOT NULL,
    title           TEXT,
    description     TEXT        NOT NULL,
    icon_url        TEXT,
    primary_color   CHAR(7)              -- "#A1B2C3"
        CHECK (primary_color IS NULL OR primary_color ~ '^#[0-9A-Fa-f]{6}$')
);

-- Race ↔ Drinks affinity
CREATE TABLE race_drinks (
    race_id     BIGINT NOT NULL REFERENCES races(id)  ON DELETE CASCADE,
    drink_id    BIGINT NOT NULL REFERENCES drinks(id) ON DELETE CASCADE,
    weight      SMALLINT NOT NULL DEFAULT 1 CHECK (weight BETWEEN 1 AND 10),
    PRIMARY KEY (race_id, drink_id)
);

-- Race ↔ Vibes affinity
CREATE TABLE race_vibes (
    race_id     BIGINT NOT NULL REFERENCES races(id) ON DELETE CASCADE,
    vibe_id     BIGINT NOT NULL REFERENCES vibes(id) ON DELETE CASCADE,
    PRIMARY KEY (race_id, vibe_id)
);


-- =====================================================================
-- 2. Users & authentication
-- =====================================================================

CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name        TEXT          NOT NULL,
    last_name         TEXT,
    username          CITEXT        NOT NULL UNIQUE,
    email             CITEXT        NOT NULL UNIQUE,
    email_verified_at TIMESTAMPTZ,
    password_hash     TEXT          NOT NULL,
    avatar_url        TEXT,

    main_city_id      BIGINT        NOT NULL REFERENCES cities(id) ON DELETE RESTRICT,
    race_id           BIGINT                 REFERENCES races(id)  ON DELETE SET NULL,

    role              user_role     NOT NULL DEFAULT 'user',
    is_active         BOOLEAN       NOT NULL DEFAULT TRUE,

    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    last_login_at     TIMESTAMPTZ,
    deleted_at        TIMESTAMPTZ
);

CREATE INDEX idx_users_main_city  ON users(main_city_id);
CREATE INDEX idx_users_race       ON users(race_id);
CREATE INDEX idx_users_active     ON users(is_active) WHERE deleted_at IS NULL;

-- JWT refresh tokens (we hash the token before storing — never store raw)
CREATE TABLE refresh_tokens (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash    TEXT         NOT NULL UNIQUE,
    expires_at    TIMESTAMPTZ  NOT NULL,
    revoked_at    TIMESTAMPTZ,
    ip_address    INET,
    user_agent    TEXT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_refresh_tokens_user   ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_active ON refresh_tokens(user_id) WHERE revoked_at IS NULL;

-- Push notification device tokens (Expo / APNs / FCM)
CREATE TABLE push_tokens (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token         TEXT          NOT NULL UNIQUE,
    platform      push_platform NOT NULL,
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    last_used_at  TIMESTAMPTZ
);

CREATE INDEX idx_push_tokens_user ON push_tokens(user_id) WHERE is_active;


-- =====================================================================
-- 3. Bars  (catalog, photos, reviews, favorites)
-- =====================================================================

CREATE TABLE bars (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            TEXT            NOT NULL UNIQUE,
    name            TEXT            NOT NULL,
    city_id         BIGINT          NOT NULL REFERENCES cities(id) ON DELETE RESTRICT,

    address         TEXT,
    location        GEOGRAPHY(POINT, 4326),

    description     TEXT,
    phone           TEXT,
    website         TEXT,
    image_url       TEXT,

    price_category  price_category  NOT NULL DEFAULT 'mid',

    -- Denormalized rating cache, refreshed via trigger / job
    rating_avg      NUMERIC(3,2)    NOT NULL DEFAULT 0.00
                                    CHECK (rating_avg >= 0 AND rating_avg <= 5),
    rating_count    INTEGER         NOT NULL DEFAULT 0
                                    CHECK (rating_count >= 0),

    -- Weekly schedule, e.g. {"mon":{"open":"12:00","close":"23:00"}, ...}
    work_hours      JSONB           NOT NULL DEFAULT '{}'::jsonb,

    -- Full-text search vector (name + description + address), maintained by trigger
    search_vector   tsvector,

    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE INDEX idx_bars_city          ON bars(city_id);
CREATE INDEX idx_bars_price         ON bars(price_category);
CREATE INDEX idx_bars_rating        ON bars(rating_avg DESC) WHERE is_active AND deleted_at IS NULL;
CREATE INDEX idx_bars_location      ON bars USING GIST (location);
CREATE INDEX idx_bars_search        ON bars USING GIN  (search_vector);
CREATE INDEX idx_bars_name_trgm     ON bars USING GIN  (name gin_trgm_ops);

CREATE FUNCTION bars_search_vector_update() RETURNS TRIGGER AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('simple', coalesce(NEW.name,       '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(NEW.description,'')), 'B') ||
        setweight(to_tsvector('simple', coalesce(NEW.address,    '')), 'C');
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER bars_search_vector_trigger
    BEFORE INSERT OR UPDATE OF name, description, address
    ON bars
    FOR EACH ROW EXECUTE FUNCTION bars_search_vector_update();

-- Bar ↔ Vibes
CREATE TABLE bar_vibes (
    bar_id   BIGINT NOT NULL REFERENCES bars(id)  ON DELETE CASCADE,
    vibe_id  BIGINT NOT NULL REFERENCES vibes(id) ON DELETE CASCADE,
    PRIMARY KEY (bar_id, vibe_id)
);

CREATE TABLE bar_photos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bar_id      BIGINT      NOT NULL REFERENCES bars(id) ON DELETE CASCADE,
    url         TEXT        NOT NULL,
    alt_text    TEXT,
    position    SMALLINT    NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_bar_photos_bar ON bar_photos(bar_id, position);

CREATE TABLE bar_reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bar_id      BIGINT      NOT NULL REFERENCES bars(id)  ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating      SMALLINT    NOT NULL CHECK (rating BETWEEN 1 AND 5),
    text        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- one review per (user, bar) — UPSERT to edit
    UNIQUE (bar_id, user_id)
);

CREATE INDEX idx_bar_reviews_bar  ON bar_reviews(bar_id);
CREATE INDEX idx_bar_reviews_user ON bar_reviews(user_id);

-- Favorites (heart button)
CREATE TABLE bar_favorites (
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bar_id      BIGINT      NOT NULL REFERENCES bars(id)  ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, bar_id)
);

CREATE INDEX idx_bar_favorites_bar ON bar_favorites(bar_id);


-- =====================================================================
-- 4. Quiz & race assignment
-- =====================================================================

CREATE TABLE quiz_questions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position    SMALLINT    NOT NULL UNIQUE CHECK (position > 0),
    text        TEXT        NOT NULL,
    image_url   TEXT,
    is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE quiz_answers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id  BIGINT      NOT NULL REFERENCES quiz_questions(id) ON DELETE CASCADE,
    text         TEXT        NOT NULL,
    position     SMALLINT    NOT NULL DEFAULT 0,

    UNIQUE (question_id, position)
);

CREATE INDEX idx_quiz_answers_question ON quiz_answers(question_id);

-- Each answer awards points to one or more races
CREATE TABLE quiz_answer_races (
    answer_id   BIGINT  NOT NULL REFERENCES quiz_answers(id) ON DELETE CASCADE,
    race_id     BIGINT  NOT NULL REFERENCES races(id)        ON DELETE CASCADE,
    score       SMALLINT NOT NULL DEFAULT 1 CHECK (score >= 0),
    PRIMARY KEY (answer_id, race_id)
);

CREATE INDEX idx_quiz_answer_races_race ON quiz_answer_races(race_id);

-- Quiz completion history (a user can retake)
CREATE TABLE user_quiz_results (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    race_id       BIGINT      NOT NULL REFERENCES races(id) ON DELETE RESTRICT,
    score_breakdown JSONB     NOT NULL DEFAULT '{}'::jsonb,  -- {race_id: total_score}
    completed_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_user_quiz_results_user ON user_quiz_results(user_id, completed_at DESC);


-- =====================================================================
-- 5. Social: friends, friend requests, friend groups
-- =====================================================================

-- Friendship is symmetric — once accepted we insert two rows so queries are simple.
CREATE TABLE user_friends (
    user_id     BIGINT             NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    friend_id   BIGINT             NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status      friendship_status  NOT NULL DEFAULT 'accepted',
    nickname    TEXT,
    is_muted    BOOLEAN            NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ        NOT NULL DEFAULT now(),
    accepted_at TIMESTAMPTZ,
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT chk_user_friends_not_self CHECK (user_id <> friend_id)
);

CREATE INDEX idx_user_friends_friend ON user_friends(friend_id);

CREATE TABLE friend_requests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id     BIGINT                 NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_id  BIGINT                 NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message       TEXT,
    status        friend_request_status  NOT NULL DEFAULT 'pending',
    created_at    TIMESTAMPTZ            NOT NULL DEFAULT now(),
    responded_at  TIMESTAMPTZ,

    CONSTRAINT chk_friend_requests_not_self CHECK (sender_id <> recipient_id)
);

-- Only one pending request between an ordered pair at a time
CREATE UNIQUE INDEX uq_friend_requests_pending
    ON friend_requests(sender_id, recipient_id)
    WHERE status = 'pending';

CREATE INDEX idx_friend_requests_recipient ON friend_requests(recipient_id, status);

-- Custom friend groups ("Party for Dungeon")
CREATE TABLE friend_groups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name        TEXT        NOT NULL,
    slug        TEXT,
    description TEXT,
    image_url   TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_friend_groups_owner ON friend_groups(owner_id);

CREATE TABLE friend_group_members (
    group_id    BIGINT             NOT NULL REFERENCES friend_groups(id) ON DELETE CASCADE,
    user_id     BIGINT             NOT NULL REFERENCES users(id)         ON DELETE CASCADE,
    role        friend_group_role  NOT NULL DEFAULT 'member',
    joined_at   TIMESTAMPTZ        NOT NULL DEFAULT now(),
    PRIMARY KEY (group_id, user_id)
);

CREATE INDEX idx_friend_group_members_user ON friend_group_members(user_id);


-- =====================================================================
-- 6. Raids (events / planned gatherings)
-- =====================================================================

CREATE TABLE raids (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             TEXT          NOT NULL,
    description       TEXT,
    bar_id            BIGINT                 REFERENCES bars(id)  ON DELETE SET NULL,
    organizer_id      BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- override location for raids not at a catalogued bar
    location          GEOGRAPHY(POINT, 4326),
    scheduled_at      TIMESTAMPTZ   NOT NULL,
    ends_at           TIMESTAMPTZ,
    max_participants  INTEGER       CHECK (max_participants IS NULL OR max_participants > 0),
    status            raid_status   NOT NULL DEFAULT 'planned',
    cover_image_url   TEXT,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_raids_scheduled  ON raids(scheduled_at) WHERE status IN ('planned','ongoing');
CREATE INDEX idx_raids_organizer  ON raids(organizer_id);
CREATE INDEX idx_raids_bar        ON raids(bar_id);
CREATE INDEX idx_raids_location   ON raids USING GIST (location);

CREATE TABLE raid_participants (
    raid_id     BIGINT             NOT NULL REFERENCES raids(id) ON DELETE CASCADE,
    user_id     BIGINT             NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status      raid_rsvp_status   NOT NULL DEFAULT 'going',
    joined_at   TIMESTAMPTZ        NOT NULL DEFAULT now(),
    PRIMARY KEY (raid_id, user_id)
);

CREATE INDEX idx_raid_participants_user ON raid_participants(user_id);


-- =====================================================================
-- 7. Checks / receipts and split
-- =====================================================================

CREATE TABLE checks (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bar_id              BIGINT                REFERENCES bars(id)  ON DELETE SET NULL,
    -- when the bar isn't in our catalog, capture freeform name from receipt
    bar_name_freeform   TEXT,
    currency            CHAR(3)      NOT NULL DEFAULT 'UAH',
    total_amount        NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),
    image_url           TEXT,
    -- Raw response from OpenAI Vision (or alternative OCR)
    ocr_payload         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    parsed_at           TIMESTAMPTZ,
    occurred_at         TIMESTAMPTZ,                                 -- the date on the receipt
    note                TEXT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ
);

CREATE INDEX idx_checks_user      ON checks(user_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_checks_bar       ON checks(bar_id);

CREATE TABLE check_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_id      BIGINT        NOT NULL REFERENCES checks(id) ON DELETE CASCADE,
    name          TEXT          NOT NULL,
    quantity      NUMERIC(10,2) NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price    NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    total_price   NUMERIC(12,2) NOT NULL CHECK (total_price >= 0),
    position      SMALLINT      NOT NULL DEFAULT 0
);

CREATE INDEX idx_check_items_check ON check_items(check_id, position);

-- Participants in a split. May be a registered user (invited via the room flow)
-- or just a guest name added manually by the host.
CREATE TABLE check_participants (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_id      BIGINT                   NOT NULL REFERENCES checks(id) ON DELETE CASCADE,
    user_id       BIGINT                            REFERENCES users(id)  ON DELETE SET NULL,
    display_name  TEXT                     NOT NULL,
    color         CHAR(7) CHECK (color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$'),  -- "#RRGGBB" for UI

    -- Split-room lifecycle:
    --   'invited' — registered user, notified, not yet in the room
    --   'joined'  — actively marking items (also the default for guests)
    --   'ready'   — finished marking; waiting for the room to close
    --   'left'    — declined invitation or left the room
    status        check_participant_status NOT NULL DEFAULT 'invited',
    joined_at     TIMESTAMPTZ,
    ready_at      TIMESTAMPTZ,
    left_at       TIMESTAMPTZ,

    created_at    TIMESTAMPTZ              NOT NULL DEFAULT now(),

    UNIQUE (check_id, display_name),
    -- Guests are joined immediately; registered users start invited.
    CONSTRAINT chk_check_participants_guest_status
        CHECK (user_id IS NOT NULL OR status IN ('joined', 'left'))
);

CREATE INDEX idx_check_participants_user_status
    ON check_participants(user_id, status)
    WHERE user_id IS NOT NULL;

CREATE INDEX idx_check_participants_check ON check_participants(check_id);
CREATE INDEX idx_check_participants_user  ON check_participants(user_id);

CREATE TABLE check_item_assignments (
    check_item_id   BIGINT        NOT NULL REFERENCES check_items(id)        ON DELETE CASCADE,
    participant_id  BIGINT        NOT NULL REFERENCES check_participants(id) ON DELETE CASCADE,
    quantity        NUMERIC(10,2) NOT NULL DEFAULT 1 CHECK (quantity > 0),
    amount          NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    PRIMARY KEY (check_item_id, participant_id)
);

CREATE INDEX idx_check_assignments_participant ON check_item_assignments(participant_id);

-- "Choose One to Pay for All" requires unanimous consent from all registered
-- participants in the split. A proposal records that consent process; the
-- D20 dice game only runs if every vote is 'accept'.
CREATE TABLE dice_proposals (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_id     BIGINT                NOT NULL REFERENCES checks(id) ON DELETE CASCADE,
    proposed_by  BIGINT                NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    status       dice_proposal_status  NOT NULL DEFAULT 'pending',
    decided_at   TIMESTAMPTZ,
    -- when status='cancelled' (e.g. a voter left the room), why
    cancel_reason TEXT,
    created_at   TIMESTAMPTZ           NOT NULL DEFAULT now()
);

-- Only one pending proposal per check at a time.
CREATE UNIQUE INDEX uq_dice_proposals_pending
    ON dice_proposals(check_id) WHERE status = 'pending';
CREATE INDEX idx_dice_proposals_check ON dice_proposals(check_id, created_at DESC);

-- One vote row per registered participant per proposal.
-- A row is inserted with vote='pending' when the proposal is created.
CREATE TABLE dice_proposal_votes (
    proposal_id  BIGINT       NOT NULL REFERENCES dice_proposals(id) ON DELETE CASCADE,
    user_id      BIGINT       NOT NULL REFERENCES users(id)          ON DELETE CASCADE,
    vote         dice_vote    NOT NULL DEFAULT 'pending',
    voted_at     TIMESTAMPTZ,
    PRIMARY KEY (proposal_id, user_id)
);

CREATE INDEX idx_dice_proposal_votes_user ON dice_proposal_votes(user_id);

-- D20 dice "Choose One to Pay for All" outcomes
-- Drives the "Добра Душа" (Kind Soul) leaderboard. A row is inserted only
-- after a dice_proposals row reaches status='accepted' and the dice is rolled.
CREATE TABLE kind_soul_events (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_id               BIGINT                NOT NULL REFERENCES checks(id) ON DELETE CASCADE,
    proposal_id            BIGINT                         REFERENCES dice_proposals(id) ON DELETE SET NULL,
    payer_user_id          BIGINT                NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    payer_participant_id   BIGINT                         REFERENCES check_participants(id) ON DELETE SET NULL,
    total_paid_for_others  NUMERIC(12,2)         NOT NULL CHECK (total_paid_for_others >= 0),
    decided_via            check_payment_method  NOT NULL DEFAULT 'd20_dice',
    -- per-participant dice rolls and any other audit data
    metadata               JSONB                 NOT NULL DEFAULT '{}'::jsonb,
    occurred_at            TIMESTAMPTZ           NOT NULL DEFAULT now(),

    UNIQUE (check_id)   -- one kind-soul event per check
);

CREATE INDEX idx_kind_soul_user ON kind_soul_events(payer_user_id, occurred_at DESC);


-- =====================================================================
-- 8. Achievements & gamification
-- =====================================================================

CREATE TABLE achievements (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              TEXT                    NOT NULL UNIQUE,    -- 'FIRST_RAID', 'KIND_SOUL_10', ...
    name              TEXT                    NOT NULL,
    description       TEXT                    NOT NULL,
    category          achievement_category    NOT NULL,
    race_id           BIGINT                  REFERENCES races(id) ON DELETE SET NULL,
    icon_url          TEXT,
    points            INTEGER                 NOT NULL DEFAULT 0,
    -- e.g. {"type":"check_count","threshold":10} or {"type":"kind_soul_total","threshold":1000}
    requirement       JSONB                   NOT NULL DEFAULT '{}'::jsonb,
    is_active         BOOLEAN                 NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ             NOT NULL DEFAULT now()
);

CREATE INDEX idx_achievements_category ON achievements(category) WHERE is_active;
CREATE INDEX idx_achievements_race     ON achievements(race_id);

CREATE TABLE user_achievements (
    user_id          BIGINT      NOT NULL REFERENCES users(id)        ON DELETE CASCADE,
    achievement_id   BIGINT      NOT NULL REFERENCES achievements(id) ON DELETE CASCADE,
    awarded_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- counters / partial progress while not yet unlocked
    progress         JSONB       NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (user_id, achievement_id)
);

CREATE INDEX idx_user_achievements_user ON user_achievements(user_id, awarded_at DESC);


-- =====================================================================
-- 9. Notifications
-- =====================================================================

CREATE TABLE notifications (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id          BIGINT             NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sender_id             BIGINT                      REFERENCES users(id) ON DELETE SET NULL,
    type                  notification_type  NOT NULL,
    title                 TEXT               NOT NULL,
    body                  TEXT,
    data                  JSONB              NOT NULL DEFAULT '{}'::jsonb,
    related_entity_type   TEXT,            -- e.g. 'raid', 'check', 'friend_request'
    related_entity_id     BIGINT,
    read_at               TIMESTAMPTZ,
    created_at            TIMESTAMPTZ        NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_recipient        ON notifications(recipient_id, created_at DESC);
CREATE INDEX idx_notifications_recipient_unread ON notifications(recipient_id) WHERE read_at IS NULL;


-- =====================================================================
-- 10. Chat & messaging (real-time over WebSockets)
-- =====================================================================

CREATE TABLE conversations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            conversation_type NOT NULL,
    -- Group chats may be backed by an existing friend_group (1:1 nullable link)
    friend_group_id BIGINT             UNIQUE REFERENCES friend_groups(id) ON DELETE SET NULL,
    -- Group chats automatically attached to a raid (1:1 nullable link)
    raid_id         BIGINT             UNIQUE REFERENCES raids(id) ON DELETE CASCADE,
    title           TEXT,                       -- group chats only
    image_url       TEXT,
    last_message_at TIMESTAMPTZ,                -- maintained by trigger
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_conversations_last_message ON conversations(last_message_at DESC NULLS LAST);

CREATE TABLE conversation_participants (
    conversation_id BIGINT             NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_id         BIGINT             NOT NULL REFERENCES users(id)         ON DELETE CASCADE,
    role               conversation_role  NOT NULL DEFAULT 'member',
    is_muted           BOOLEAN            NOT NULL DEFAULT FALSE,
    last_delivered_at  TIMESTAMPTZ,         -- newest message confirmed reaching this user's device
    last_read_at       TIMESTAMPTZ,         -- newest message this user has read
    joined_at          TIMESTAMPTZ        NOT NULL DEFAULT now(),
    left_at            TIMESTAMPTZ,
    PRIMARY KEY (conversation_id, user_id)
);

CREATE INDEX idx_conversation_participants_user
    ON conversation_participants(user_id)
    WHERE left_at IS NULL;

CREATE TABLE messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT      NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id       BIGINT      NOT NULL REFERENCES users(id)         ON DELETE CASCADE,
    body            TEXT,
    -- [{url, type, name, size}] for images / files attached to a message
    attachments     JSONB       NOT NULL DEFAULT '[]'::jsonb,
    reply_to_id     BIGINT               REFERENCES messages(id) ON DELETE SET NULL,
    edited_at       TIMESTAMPTZ,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- a message must carry text OR at least one attachment
    CONSTRAINT chk_messages_has_content
        CHECK (body IS NOT NULL OR jsonb_array_length(attachments) > 0)
);

CREATE INDEX idx_messages_conversation ON messages(conversation_id, created_at DESC);
CREATE INDEX idx_messages_sender       ON messages(sender_id);

-- Optional emoji reactions on a message
CREATE TABLE message_reactions (
    message_id  BIGINT      NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    emoji       TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (message_id, user_id, emoji)
);

-- Live presence used by the chat list (green dot) — updated by the WebSocket layer
CREATE TABLE user_presence (
    user_id      BIGINT          PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    status       presence_status NOT NULL DEFAULT 'offline',
    last_seen_at TIMESTAMPTZ     NOT NULL DEFAULT now()
);

-- Bump conversations.last_message_at on every new message so chat lists sort cheaply
CREATE FUNCTION conversations_touch_last_message() RETURNS TRIGGER AS $$
BEGIN
    UPDATE conversations
       SET last_message_at = NEW.created_at,
           updated_at      = now()
     WHERE id = NEW.conversation_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_messages_touch_conversation
    AFTER INSERT ON messages
    FOR EACH ROW EXECUTE FUNCTION conversations_touch_last_message();


-- =====================================================================
-- 11. Tavern Tales — AI Dungeon Master (single-player, OpenAI GPT-4o)
-- =====================================================================

-- Reference table — the twelve D&D 5e player classes, surfaced in the
-- character-creation picker. Seeded once and rarely changes.
CREATE TABLE dnd_class_info (
    slug             dnd_class  PRIMARY KEY,
    name             TEXT       NOT NULL,
    description      TEXT       NOT NULL,
    hit_die          SMALLINT   NOT NULL CHECK (hit_die IN (6, 8, 10, 12)),
    primary_ability  TEXT,
    icon_url         TEXT
);

-- A player's character. Race comes from the user's quiz result; class is
-- chosen during creation. AI updates HP / XP / inventory as quests resolve.
CREATE TABLE dnd_characters (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    race_id         BIGINT          NOT NULL REFERENCES races(id) ON DELETE RESTRICT,
    class_slug      dnd_class       NOT NULL REFERENCES dnd_class_info(slug),
    name            TEXT            NOT NULL,
    level           SMALLINT        NOT NULL DEFAULT 1 CHECK (level BETWEEN 1 AND 20),
    xp              INTEGER         NOT NULL DEFAULT 0 CHECK (xp >= 0),
    alignment       dnd_alignment,

    -- D&D 5e ability scores: {"str":14,"dex":12,"con":15,"int":10,"wis":13,"cha":16}
    stats           JSONB           NOT NULL DEFAULT '{}'::jsonb,
    hp_current      INTEGER         NOT NULL DEFAULT 10 CHECK (hp_current >= 0),
    hp_max          INTEGER         NOT NULL DEFAULT 10 CHECK (hp_max > 0),
    armor_class     SMALLINT        NOT NULL DEFAULT 10 CHECK (armor_class >= 0),

    background      TEXT,
    -- e.g. [{"slug":"longsword","name":"Longsword","qty":1}]
    inventory       JSONB           NOT NULL DEFAULT '[]'::jsonb,
    -- e.g. [{"slug":"firebolt","name":"Fire Bolt","level":0}]
    spells_known    JSONB           NOT NULL DEFAULT '[]'::jsonb,

    avatar_url      TEXT,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    last_played_at  TIMESTAMPTZ,
    deleted_at      TIMESTAMPTZ,

    -- Current HP cannot exceed max HP (after healing or level-up updates).
    CONSTRAINT chk_dnd_characters_hp CHECK (hp_current <= hp_max)
);

CREATE INDEX idx_dnd_characters_user
    ON dnd_characters(user_id, last_played_at DESC NULLS LAST)
    WHERE deleted_at IS NULL;

-- A play session — one self-contained quest. AI assigns the title and keeps
-- a rolling `summary` so old turns can be evicted from the live context
-- window once the message log gets long.
CREATE TABLE dnd_sessions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id        BIGINT             NOT NULL REFERENCES dnd_characters(id) ON DELETE CASCADE,
    mode                dnd_mode           NOT NULL,
    title               TEXT,
    summary             TEXT,
    status              dnd_session_status NOT NULL DEFAULT 'active',
    turn_count          INTEGER            NOT NULL DEFAULT 0,
    input_tokens_used   INTEGER            NOT NULL DEFAULT 0,
    output_tokens_used  INTEGER            NOT NULL DEFAULT 0,
    -- world state — e.g. {"location":"Goblin cave","objective":"Find amulet"}
    metadata            JSONB              NOT NULL DEFAULT '{}'::jsonb,

    started_at          TIMESTAMPTZ        NOT NULL DEFAULT now(),
    last_message_at     TIMESTAMPTZ,
    ended_at            TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ        NOT NULL DEFAULT now()
);

CREATE INDEX idx_dnd_sessions_character ON dnd_sessions(character_id, started_at DESC);

-- Only one active or paused session per character — pick one quest at a time.
CREATE UNIQUE INDEX uq_dnd_sessions_one_in_progress
    ON dnd_sessions(character_id) WHERE status IN ('active','paused');

-- Turn-by-turn message log. Includes dice rolls and system narration as
-- distinct roles so the UI can render them with their own styling.
CREATE TABLE dnd_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      BIGINT             NOT NULL REFERENCES dnd_sessions(id) ON DELETE CASCADE,
    role            dnd_message_role   NOT NULL,
    content         TEXT               NOT NULL,
    -- role-specific structured data:
    --   dice_roll : {"dice":"d20","modifier":3,"result":17,"purpose":"persuasion"}
    --   assistant : optional {"state_change":{"hp_delta":-5,"loot":[...]}, "request_roll":{"dice":"d20","dc":15}}
    metadata        JSONB              NOT NULL DEFAULT '{}'::jsonb,
    tokens_in       INTEGER,
    tokens_out      INTEGER,
    created_at      TIMESTAMPTZ        NOT NULL DEFAULT now()
);

CREATE INDEX idx_dnd_messages_session ON dnd_messages(session_id, created_at);

-- Per-user LLM cost cap so a runaway loop or abusive client can't drain the
-- budget. Counters are reset by a daily/monthly task; the API rejects new
-- turns when a limit is hit and surfaces "you've used X of Y today".
CREATE TABLE dnd_usage_quota (
    user_id               BIGINT       PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    daily_tokens_used     INTEGER      NOT NULL DEFAULT 0,
    daily_tokens_limit    INTEGER      NOT NULL DEFAULT 30000,
    daily_reset_at        DATE         NOT NULL DEFAULT CURRENT_DATE,
    monthly_tokens_used   INTEGER      NOT NULL DEFAULT 0,
    monthly_tokens_limit  INTEGER      NOT NULL DEFAULT 500000,
    monthly_reset_at      DATE         NOT NULL DEFAULT (date_trunc('month', CURRENT_DATE)::date),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);


-- =====================================================================
-- 11b. Triggers that maintain denormalized caches
-- =====================================================================

-- Keep bars.rating_avg / rating_count in sync with bar_reviews. Fires on every
-- review insert / update / delete and recomputes the cached values for that bar
-- in a single statement. AVG returns NULL when the bar has no reviews left,
-- so we COALESCE to 0.
CREATE FUNCTION bars_refresh_rating_cache() RETURNS TRIGGER AS $$
DECLARE
    target_bar BIGINT;
BEGIN
    target_bar := COALESCE(NEW.bar_id, OLD.bar_id);
    UPDATE bars
       SET rating_avg   = COALESCE((SELECT ROUND(AVG(rating)::numeric, 2)
                                      FROM bar_reviews
                                     WHERE bar_id = target_bar), 0),
           rating_count = (SELECT COUNT(*)
                             FROM bar_reviews
                            WHERE bar_id = target_bar)
     WHERE id = target_bar;
    RETURN NULL;          -- AFTER trigger, return value is ignored
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_bar_reviews_refresh_cache
    AFTER INSERT OR UPDATE OR DELETE
    ON bar_reviews
    FOR EACH ROW EXECUTE FUNCTION bars_refresh_rating_cache();


-- =====================================================================
-- 12. Shared updated_at trigger (apply to mutable tables)
-- =====================================================================

CREATE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_cities_updated_at        BEFORE UPDATE ON cities         FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_users_updated_at         BEFORE UPDATE ON users          FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_bar_reviews_updated_at   BEFORE UPDATE ON bar_reviews    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_friend_groups_updated_at BEFORE UPDATE ON friend_groups  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_raids_updated_at         BEFORE UPDATE ON raids          FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_checks_updated_at        BEFORE UPDATE ON checks         FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_conversations_updated_at BEFORE UPDATE ON conversations   FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_dnd_characters_updated_at  BEFORE UPDATE ON dnd_characters  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_dnd_sessions_updated_at    BEFORE UPDATE ON dnd_sessions    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_dnd_usage_quota_updated_at BEFORE UPDATE ON dnd_usage_quota FOR EACH ROW EXECUTE FUNCTION set_updated_at();
-- bars uses its own trigger (bars_search_vector_trigger) which already sets updated_at.

-- End of schema.
