"""profile foundation — bio, social rating, attendance stats, interests

Revision ID: 0002_profile_interests
Revises: 0001_baseline
Create Date: 2026-06-08 00:00:00.000000

WP1 of the finishing plan. Adds the profile fields every social feature
depends on:

  * users.bio              — free-text "about me"
  * users.social_rating    — starts at 100; no-shows will dock points (WP6)
  * users.events_attended  — lifetime count of verified attendances
  * users.events_ditched   — lifetime count of RSVP'd-but-no-show events

  * interests              — catalog of selectable interest chips
  * user_interests         — M2M between users and interests

Incremental revision (never edit schema.sql in place). The downgrade is a
precise reverse of the upgrade.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0002_profile_interests"
down_revision: str | Sequence[str] | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Seed chips so the app has something to show on day one. Slugs are stable
# identifiers; labels are what the UI renders.
_SEED_INTERESTS: list[tuple[str, str]] = [
    ("tabletop_games", "Tabletop Games"),
    ("dnd", "D&D"),
    ("board_games", "Board Games"),
    ("hiking", "Hiking"),
    ("live_music", "Live Music"),
    ("karaoke", "Karaoke"),
    ("craft_beer", "Craft Beer"),
    ("wine_tasting", "Wine Tasting"),
    ("cocktails", "Cocktails"),
    ("sports", "Sports"),
    ("esports", "Esports"),
    ("video_games", "Video Games"),
    ("movies", "Movies"),
    ("foodie", "Foodie"),
    ("coffee", "Coffee"),
    ("dancing", "Dancing"),
    ("standup", "Stand-up Comedy"),
    ("photography", "Photography"),
    ("books", "Books"),
    ("anime", "Anime"),
]


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE users
            ADD COLUMN IF NOT EXISTS bio             TEXT,
            ADD COLUMN IF NOT EXISTS social_rating   INTEGER NOT NULL DEFAULT 100,
            ADD COLUMN IF NOT EXISTS events_attended INTEGER NOT NULL DEFAULT 0,
            ADD COLUMN IF NOT EXISTS events_ditched  INTEGER NOT NULL DEFAULT 0;
        """
    )
    op.execute(
        """
        ALTER TABLE users
            ADD CONSTRAINT chk_users_social_rating
            CHECK (social_rating BETWEEN 0 AND 1000);
        """
    )

    op.execute(
        """
        CREATE TABLE interests (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            slug        TEXT        NOT NULL UNIQUE,
            label       TEXT        NOT NULL,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )

    op.execute(
        """
        CREATE TABLE user_interests (
            user_id     BIGINT      NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
            interest_id BIGINT      NOT NULL REFERENCES interests(id) ON DELETE CASCADE,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (user_id, interest_id)
        );
        """
    )
    op.execute("CREATE INDEX idx_user_interests_interest ON user_interests(interest_id);")

    # Seed the catalog.
    values = ", ".join(
        f"('{slug}', '{label}')" for slug, label in _SEED_INTERESTS
    )
    op.execute(
        f"INSERT INTO interests (slug, label) VALUES {values} "
        f"ON CONFLICT (slug) DO NOTHING;"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS user_interests;")
    op.execute("DROP TABLE IF EXISTS interests;")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_social_rating;")
    op.execute(
        """
        ALTER TABLE users
            DROP COLUMN IF EXISTS bio,
            DROP COLUMN IF EXISTS social_rating,
            DROP COLUMN IF EXISTS events_attended,
            DROP COLUMN IF EXISTS events_ditched;
        """
    )
