"""parties — "looking for party members" with interest matching

Revision ID: 0004_parties
Revises: 0003_raid_lifecycle
Create Date: 2026-06-08 00:00:00.000000

WP3 of the finishing plan. A Party is a lightweight, venue-optional gathering
people discover by shared interests — distinct from a Raid (which is tied to a
time/place and runs the full attendance lifecycle).

  * parties          — host, title, description, max_members, visibility, status
  * party_interests  — M2M to the interests catalog (powers matching/tags)
  * party_members    — who's in (joined / left / invited)

Also extends notification_type with 'party_invite'.

Incremental revision (never edit schema.sql in place).

NOTE on downgrade: the added 'party_invite' enum value is left in place
(Postgres can't drop an enum value without recreating the type). Everything
else is reversed.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0004_parties"
down_revision: str | Sequence[str] | None = "0003_raid_lifecycle"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Additive enum value (safe inside the migration tx on PG12+; not used here).
    op.execute(
        "ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'party_invite';"
    )

    op.execute("CREATE TYPE party_visibility AS ENUM ('open', 'friends_only');")
    op.execute("CREATE TYPE party_status AS ENUM ('open', 'closed', 'cancelled');")
    op.execute(
        "CREATE TYPE party_member_status AS ENUM ('joined', 'left', 'invited');"
    )

    op.execute(
        """
        CREATE TABLE parties (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            host_id      BIGINT          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            title        TEXT            NOT NULL,
            description  TEXT,
            max_members  INTEGER         CHECK (max_members IS NULL OR max_members > 1),
            visibility   party_visibility NOT NULL DEFAULT 'open',
            status       party_status     NOT NULL DEFAULT 'open',
            created_at   TIMESTAMPTZ     NOT NULL DEFAULT now(),
            updated_at   TIMESTAMPTZ     NOT NULL DEFAULT now()
        );
        """
    )
    op.execute("CREATE INDEX idx_parties_host ON parties(host_id);")
    op.execute("CREATE INDEX idx_parties_status ON parties(status);")

    op.execute(
        """
        CREATE TABLE party_interests (
            party_id    BIGINT NOT NULL REFERENCES parties(id)   ON DELETE CASCADE,
            interest_id BIGINT NOT NULL REFERENCES interests(id) ON DELETE CASCADE,
            PRIMARY KEY (party_id, interest_id)
        );
        """
    )
    op.execute(
        "CREATE INDEX idx_party_interests_interest ON party_interests(interest_id);"
    )

    op.execute(
        """
        CREATE TABLE party_members (
            party_id   BIGINT             NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
            user_id    BIGINT             NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
            status     party_member_status NOT NULL DEFAULT 'joined',
            joined_at  TIMESTAMPTZ        NOT NULL DEFAULT now(),
            PRIMARY KEY (party_id, user_id)
        );
        """
    )
    op.execute("CREATE INDEX idx_party_members_user ON party_members(user_id);")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS party_members;")
    op.execute("DROP TABLE IF EXISTS party_interests;")
    op.execute("DROP TABLE IF EXISTS parties;")
    op.execute("DROP TYPE IF EXISTS party_member_status;")
    op.execute("DROP TYPE IF EXISTS party_status;")
    op.execute("DROP TYPE IF EXISTS party_visibility;")
    # The added 'party_invite' notification_type value is intentionally left.
